### ISSUE TITLE
Create Search input

### ISSUE THREAD

**Issue by gusliedke** [comicrelief/component-library#104]
<img width="846" alt="Screenshot 2019-08-14 at 09 47 36" src="https://user-images.githubusercontent.com/1434022/63007412-81876d80-be78-11e9-9c06-9446ac572f9f.png">

**Comment by LouiaR** [comment]
@gusliedke should I add the close button or is not necessary?

**Comment by gusliedke** [comment]
Not necessary

**Comment by lebaz20** [comment]
@LouiaR 
I think it might be useful to check current basic search input at https://github.com/comicrelief/comicrelief-contentful/blob/06ee1abdee24dcf116efc812c53594efcbf567db/src/components/Search/SearchBox.js
at https://github.com/comicrelief/comicrelief-contentful/pull/106
preview: https://deploy-preview-106--comicrelief-contentful.netlify.com/search
