### ISSUE TITLE
[CompLib.] Update tickbox styling

### ISSUE THREAD

**Issue by Ruby-HB** [comicrelief/component-library#368]
![image](https://user-images.githubusercontent.com/59445264/94837756-91f80000-040c-11eb-85cc-938dfb69e892.png)

**Comment by gusliedke** [comment]
What's the checked state?
![image](https://user-images.githubusercontent.com/1434022/94907038-7554da00-0497-11eb-9692-a0bdfd3d1b02.png)

**Comment by Ruby-HB** [comment]
I have a style designed, but I think I may change this to have a white tick on red bgd - I will spec this soon and update here :)

**Comment by gusliedke** [comment]
how about it?
![image](https://user-images.githubusercontent.com/1434022/94908916-47bd6000-049a-11eb-87b6-2871c4ef2613.png)

**Comment by Ruby-HB** [comment]
I like it! Is there any way of increasing the tick line weight? So the tick is a tiny bit thicker?

**Comment by gusliedke** [comment]
just checked it is a png.. can you create a svg tick please?

**Comment by Ruby-HB** [comment]
Ah sure, I think I have one done already, I'll send it over slack
