### ISSUE TITLE
Email CTA button - @ icon

### ISSUE THREAD

**Issue by Ruby-HB** [comicrelief/component-library#379]
- [x] Please add the @ symbol to CTAs that link to an email address

![image](https://user-images.githubusercontent.com/59445264/97172614-27c24900-1787-11eb-9d5a-a792147d48f1.png)

- [x] download Icon on Cards
![image](https://user-images.githubusercontent.com/1434022/107962551-0045f500-6f9f-11eb-8b99-112ce2379c3f.png)

**Comment by tomisaacmarshall** [comment]
Can anyone point me to the places on the website where these icons should appear? @Ruby-HB @gusliedke

**Comment by Ruby-HB** [comment]
Hi @tomisaacmarshall I need to create a home for these icons (just reluctant to use a Box folder haha)
I've been using Figma which you can export from, but it's not up-to-date.
So in conclusion, I will send you the email SVG over Slack! :)

**Comment by tomisaacmarshall** [comment]
Re the download icon, we need to decide when to show it rather than the link icon, but there isn't really any difference between a CTA that says 'download x' and one that says 'open link' - they are both just links.

One simple option would be show download the icon for any CTA that begins with (or contains?) the word 'download' - does that sound ok?

**Comment by gusliedke** [comment]
I agree with the label containing "download".

**Comment by Ruby-HB** [comment]
Hmm can we not attach it to the type of file uploaded? So if it's a PDF or JPG link? (I understand it might not be able to distinguish in this way though)

**Comment by gusliedke** [comment]
@tomisaacmarshall we could add a new field to use (ref) and only allow files .. we had problems using ref link for page due some loop issues. Using ref for the files we would get type and size which we could include on the buttons `Dowload poster (124kb) .jpg ⬇️ `

**Comment by tomisaacmarshall** [comment]
Yes the most robust way of doing it is to update the CMS so that people are specifically saying 'this is a file download' when adding the content - lets go with that.

**Comment by Ruby-HB** [comment]
Ah cool so it actually might make sense to make this a manual choice on Contentful?
@gusliedke are you okay to add this option to components with links? :)

**Comment by gusliedke** [comment]
Any link in richText is dealt differently. We can do this on CardsDS and SingleMsgDS.

**Comment by Ruby-HB** [comment]
Okay sounds good, thanks Gus :)

**Comment by tomisaacmarshall** [comment]
All done for CardDs and SingleMessageDs
