### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by gusliedke** [comicrelief/component-library#40]
![Screenshot 2019-07-03 at 16 36 11](https://user-images.githubusercontent.com/1434022/60605069-c1a2fd00-9db0-11e9-95ca-a848081027df.png)

**Comment by lebaz20** [comment]
Here's an example of how it looks like: 

![Screenshot from 2019-07-10 13-27-26](https://user-images.githubusercontent.com/5208251/60965617-822b6200-a316-11e9-8724-2760ddebdbd6.png)
